version: "3"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    volumes:
      - .:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
